####################################################################################
# in production NODE_ENV `docker compose build` not wrong with it, but when I use 
# `docker compose up` it cannot run. I dunno why.
####################################################################################

# Node API service
FROM node:lts-bullseye-slim as base

# arguments/variables inside Dockerfile
ARG WORKDIR=$WORKDIR
ARG API_PORT_EXPOSE=$API_PORT_EXPOSE
ARG NODE_ENV=$NODE_ENV

# environment for building node
ENV NODE_ENV=development

# expose port
EXPOSE $API_PORT_EXPOSE

# set workdir
WORKDIR $WORKDIR

# copy file package.json and lock file
COPY ./backend/package.json .
COPY ./backend/pnpm-lock.yaml .

# install pnpm and depencies from lock file
RUN npm install -g pnpm && pnpm install --frozen-lockfile

# copy files that we need
COPY ./backend .

# build if production
RUN if [ "$NODE_ENV" = "production" ]; then pnpm run build; fi

############################# DEVELOPMENT STAGE #############################
FROM base as development

# copy and set permission for files
COPY ./entrypoint-api.sh .
RUN chmod +x ./entrypoint-api.sh

# prisma generate
RUN pnpm dlx prisma generate;

# run entrypoint (any other command that we need)
ENTRYPOINT [ "./entrypoint-api.sh" ]

############################# PRODUCTION STAGE #############################
FROM node:lts-bullseye-slim as production

# arguments/variables inside Dockerfile
ARG WORKDIR=$WORKDIR

# environment inside Dockerfile
ENV NODE_ENV=production

# set workdir
WORKDIR $WORKDIR

# copy file package.json and lock file
COPY ./backend/package.json .
COPY ./backend/pnpm-lock.yaml .

# install pnpm and depencies from lock file
RUN npm install -g pnpm && pnpm install --frozen-lockfile --prod

# copy files that we need from build stage
COPY --from=base $WORKDIR/dist .
COPY --from=base $WORKDIR/src/databases/prisma/schema.prisma ./databases/prisma/schema.prisma
COPY --from=base $WORKDIR/.env ./.env

# prisma generate
RUN pnpm dlx prisma generate --schema=./databases/prisma/schema.prisma

# prisma seed
# RUN node ./databases/prisma/seed.js

# run server
CMD ["node", "server.js"]