version: "3.8"

services:
  # Node API service
  api:
    container_name: patroli-api
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile-api
      target: ${NODE_ENV}
      args:
        - WORKDIR=${WORKDIR}
        - API_PORT_EXPOSE=${API_PORT_EXPOSE}
        - NODE_ENV=${NODE_ENV}
    ports:
      - ${API_PORT_EXPOSE}:${API_PORT}
    volumes:
      - ./backend/entrypoint-api.sh:${WORKDIR}/entrypoint-api.sh
      - ./backend:${WORKDIR}
      - api-node_modules:${WORKDIR}/node_modules # Do not sync this file/folder
      - api-dist:${WORKDIR}/dist # Do not sync this file/folder
    env_file:
      - .env
    depends_on:
      - mongodb

  # MongoDB service
  mongodb:
    container_name: patroli-mongodb
    restart: unless-stopped
    build:
      context: ./mongodb
      dockerfile: Dockerfile-mongodb
      args:
        - WORKDIR=${WORKDIR}
        - MONGO_PORT=${MONGO_PORT}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./mongodb/entrypoint-mongodb.sh:${WORKDIR}/entrypoint-mongodb.sh
      - mongodb-data:${MONGO_PATH}
      - mongodb-configdb:${MONGO_CONFIG_PATH}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGODB_ADVERTISED_HOSTNAME=${MONGO_HOST}
    env_file:
      - .env

volumes:
  api-node_modules:
    driver: local
  api-dist:
    driver: local
  mongodb-data:
    driver: local
  mongodb-configdb:
    driver: local
