version: '3.8'

services:
  mongodb-server:
    build: 
      context: .
      dockerfile: Dockerfile
    image: mongo:5
    container_name: mongodb-server
    restart: always
    volumes:
      - mongo-server-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_REPLICA_HOST=${MONGO_REPLICA_HOST}
      - MONGO_REPLICA_PORT=${MONGO_REPLICA_PORT}
    ports:
      - ${MONGO_REPLICA_PORT}:${MONGO_REPLICA_PORT}

volumes:
  mongo-server-data:
    # external: true
    driver: local